-- MySQL Script generated by MySQL Workbench
-- Fri Oct  6 14:49:52 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sep
-- -----------------------------------------------------
-- Database for final project in Modern Methods in Software Engineering
DROP SCHEMA IF EXISTS `sep` ;

-- -----------------------------------------------------
-- Schema sep
--
-- Database for final project in Modern Methods in Software Engineering
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sep` DEFAULT CHARACTER SET utf8 ;
USE `sep` ;

-- -----------------------------------------------------
-- Table `sep`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sep`.`Client` (
  `clientRecord` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `company` VARCHAR(45) NULL,
  PRIMARY KEY (`clientRecord`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sep`.`EventRequest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sep`.`EventRequest` (
  `eventRecord` INT NOT NULL AUTO_INCREMENT,
  `eventType` VARCHAR(45) NULL,
  `eventStartDateTime` DATETIME NULL,
  `eventEndDateTime` DATETIME NULL,
  `attendees` INT NULL,
  `budget` DECIMAL(10,2) NULL,
  `status` VARCHAR(45) NULL,
  `clientRecord` INT NOT NULL,
  PRIMARY KEY (`eventRecord`),
  CONSTRAINT `fk_EventRequest_Client`
    FOREIGN KEY (`clientRecord`)
    REFERENCES `sep`.`Client` (`clientRecord`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_EventRequest_Client_idx` ON `sep`.`EventRequest` (`clientRecord` ASC);


-- -----------------------------------------------------
-- Table `sep`.`Meeting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sep`.`Meeting` (
  `idMeeting` INT NOT NULL AUTO_INCREMENT,
  `startDateTime` DATETIME NULL,
  `endDateTime` DATETIME NULL,
  `clientRecord` INT NOT NULL,
  `eventRecord` INT NOT NULL,
  PRIMARY KEY (`idMeeting`),
  CONSTRAINT `fk_Meeting_EventRequest1`
    FOREIGN KEY (`eventRecord`)
    REFERENCES `sep`.`EventRequest` (`eventRecord`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Meeting_Client1`
    FOREIGN KEY (`clientRecord`)
    REFERENCES `sep`.`Client` (`clientRecord`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Meeting_EventRequest1_idx` ON `sep`.`Meeting` (`eventRecord` ASC);

CREATE INDEX `fk_Meeting_Client1_idx` ON `sep`.`Meeting` (`clientRecord` ASC);


-- -----------------------------------------------------
-- Table `sep`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sep`.`Role` (
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sep`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sep`.`Employee` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`username`),
  CONSTRAINT `fk_Employee_Role1`
    FOREIGN KEY (`role`)
    REFERENCES `sep`.`Role` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Employee_Role1_idx` ON `sep`.`Employee` (`role` ASC);


-- -----------------------------------------------------
-- Table `sep`.`Summary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sep`.`Summary` (
  `idSummary` INT NOT NULL AUTO_INCREMENT,
  `eventType` VARCHAR(45) NULL,
  `description` MEDIUMTEXT NULL,
  `attendees` INT NULL,
  `eventStartDate` DATETIME NULL,
  `eventEndDate` DATETIME NULL,
  `budget` DECIMAL(10,2) NULL,
  `idMeeting` INT NOT NULL,
  PRIMARY KEY (`idSummary`),
  CONSTRAINT `fk_Summary_Meeting1`
    FOREIGN KEY (`idMeeting`)
    REFERENCES `sep`.`Meeting` (`idMeeting`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Summary_Meeting1_idx` ON `sep`.`Summary` (`idMeeting` ASC);


-- -----------------------------------------------------
-- Table `sep`.`Preferences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sep`.`Preferences` (
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
COMMENT = '										';


-- -----------------------------------------------------
-- Table `sep`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sep`.`Task` (
  `idTask` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(60) NULL,
  `description` MEDIUMTEXT NULL,
  `priority` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `eventRecord` INT NOT NULL,
  `creator` VARCHAR(45) NOT NULL,
  `assignee` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTask`),
  CONSTRAINT `fk_Task_EventRequest1`
    FOREIGN KEY (`eventRecord`)
    REFERENCES `sep`.`EventRequest` (`eventRecord`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_Employee1`
    FOREIGN KEY (`creator`)
    REFERENCES `sep`.`Employee` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_Employee2`
    FOREIGN KEY (`assignee`)
    REFERENCES `sep`.`Employee` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Task_EventRequest1_idx` ON `sep`.`Task` (`eventRecord` ASC);

CREATE INDEX `fk_Task_Employee1_idx` ON `sep`.`Task` (`creator` ASC);

CREATE INDEX `fk_Task_Employee2_idx` ON `sep`.`Task` (`assignee` ASC);


-- -----------------------------------------------------
-- Table `sep`.`FinancialRequest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sep`.`FinancialRequest` (
  `idFinancialRequest` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10,2) NULL,
  `reason` VARCHAR(60) NULL,
  `discount` DECIMAL(10,2) NULL,
  `agreedBudget` DECIMAL(10,2) NULL,
  `status` VARCHAR(45) NULL,
  `eventRecord` INT NOT NULL,
  `requester` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFinancialRequest`),
  CONSTRAINT `fk_FinancialRequest_EventRequest1`
    FOREIGN KEY (`eventRecord`)
    REFERENCES `sep`.`EventRequest` (`eventRecord`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FinancialRequest_Employee1`
    FOREIGN KEY (`requester`)
    REFERENCES `sep`.`Employee` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_FinancialRequest_EventRequest1_idx` ON `sep`.`FinancialRequest` (`eventRecord` ASC);

CREATE INDEX `fk_FinancialRequest_Employee1_idx` ON `sep`.`FinancialRequest` (`requester` ASC);


-- -----------------------------------------------------
-- Table `sep`.`StaffRequest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sep`.`StaffRequest` (
  `idStaffRequest` INT NOT NULL AUTO_INCREMENT,
  `experience` VARCHAR(45) NULL,
  `jobTitle` VARCHAR(45) NULL,
  `jobDescription` LONGTEXT NULL,
  `requester` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStaffRequest`),
  CONSTRAINT `fk_StaffRequest_Employee1`
    FOREIGN KEY (`requester`)
    REFERENCES `sep`.`Employee` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_StaffRequest_Employee1_idx` ON `sep`.`StaffRequest` (`requester` ASC);


-- -----------------------------------------------------
-- Table `sep`.`EventRequestPreferences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sep`.`EventRequestPreferences` (
  `eventRecord` INT NOT NULL,
  `preference` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`eventRecord`, `preference`),
  CONSTRAINT `fk_EventRequest_has_Preferences_EventRequest1`
    FOREIGN KEY (`eventRecord`)
    REFERENCES `sep`.`EventRequest` (`eventRecord`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EventRequest_has_Preferences_Preferences1`
    FOREIGN KEY (`preference`)
    REFERENCES `sep`.`Preferences` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_EventRequest_has_Preferences_Preferences1_idx` ON `sep`.`EventRequestPreferences` (`preference` ASC);

CREATE INDEX `fk_EventRequest_has_Preferences_EventRequest1_idx` ON `sep`.`EventRequestPreferences` (`eventRecord` ASC);


-- -----------------------------------------------------
-- Table `sep`.`SummaryPreferences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sep`.`SummaryPreferences` (
  `idSummary` INT NOT NULL,
  `preference` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NULL,
  PRIMARY KEY (`idSummary`, `preference`),
  CONSTRAINT `fk_Summary_has_Preferences_Summary1`
    FOREIGN KEY (`idSummary`)
    REFERENCES `sep`.`Summary` (`idSummary`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Summary_has_Preferences_Preferences1`
    FOREIGN KEY (`preference`)
    REFERENCES `sep`.`Preferences` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Summary_has_Preferences_Preferences1_idx` ON `sep`.`SummaryPreferences` (`preference` ASC);

CREATE INDEX `fk_Summary_has_Preferences_Summary1_idx` ON `sep`.`SummaryPreferences` (`idSummary` ASC);


-- -----------------------------------------------------
-- Table `sep`.`Plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sep`.`Plan` (
  `idPlan` INT NOT NULL AUTO_INCREMENT,
  `description` MEDIUMTEXT NULL,
  PRIMARY KEY (`idPlan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sep`.`PlanCoversTasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sep`.`PlanCoversTasks` (
  `idPlan` INT NOT NULL,
  `idTask` INT NOT NULL,
  `creator` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPlan`, `idTask`),
  CONSTRAINT `fk_Plan_has_Task_Plan1`
    FOREIGN KEY (`idPlan`)
    REFERENCES `sep`.`Plan` (`idPlan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plan_has_Task_Task1`
    FOREIGN KEY (`idTask`)
    REFERENCES `sep`.`Task` (`idTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlanCoversTasks_Employee1`
    FOREIGN KEY (`creator`)
    REFERENCES `sep`.`Employee` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Plan_has_Task_Task1_idx` ON `sep`.`PlanCoversTasks` (`idTask` ASC);

CREATE INDEX `fk_Plan_has_Task_Plan1_idx` ON `sep`.`PlanCoversTasks` (`idPlan` ASC);

CREATE INDEX `fk_PlanCoversTasks_Employee1_idx` ON `sep`.`PlanCoversTasks` (`creator` ASC);

CREATE USER 'common' IDENTIFIED BY 'common';

GRANT ALL ON `sep`.* TO 'common';
GRANT SELECT, INSERT, TRIGGER ON TABLE `sep`.* TO 'common';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `sep`.* TO 'common';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `sep`.`Client`
-- -----------------------------------------------------
START TRANSACTION;
USE `sep`;
INSERT INTO `sep`.`Client` (`clientRecord`, `name`, `company`) VALUES (DEFAULT, 'Bernardo Riede', 'Spotify');
INSERT INTO `sep`.`Client` (`clientRecord`, `name`, `company`) VALUES (DEFAULT, 'Vasileios Charalampidis', 'KTH');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sep`.`Role`
-- -----------------------------------------------------
START TRANSACTION;
USE `sep`;
INSERT INTO `sep`.`Role` (`name`) VALUES ('Financial Manager');
INSERT INTO `sep`.`Role` (`name`) VALUES ('Administration Manager');
INSERT INTO `sep`.`Role` (`name`) VALUES ('CSO');
INSERT INTO `sep`.`Role` (`name`) VALUES ('SCSO');
INSERT INTO `sep`.`Role` (`name`) VALUES ('Production Manager');
INSERT INTO `sep`.`Role` (`name`) VALUES ('Service Manager');
INSERT INTO `sep`.`Role` (`name`) VALUES ('HR Manager');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sep`.`Preferences`
-- -----------------------------------------------------
START TRANSACTION;
USE `sep`;
INSERT INTO `sep`.`Preferences` (`name`) VALUES ('Decorations');
INSERT INTO `sep`.`Preferences` (`name`) VALUES ('Parties');
INSERT INTO `sep`.`Preferences` (`name`) VALUES ('Photos/Filming');
INSERT INTO `sep`.`Preferences` (`name`) VALUES ('Drinks');
INSERT INTO `sep`.`Preferences` (`name`) VALUES ('Food');
INSERT INTO `sep`.`Preferences` (`name`) VALUES ('WiFi');

COMMIT;

